<?php

/**
 * @file
 * Defines utility functions for the Maine Rural Partners Project.
 */


/**
* Implements hook_entity_info_alter().
*/
function mrp_utils_entity_info_alter(&$entity_info) {
  $entity_info['node']['view modes']['bodyonly'] = array(
    'label' => t('Body only'),
    'custom settings' => TRUE,
  );
}

/**
* Implements hook_preprocess_node().
*/
function mrp_utils_preprocess_node(&$vars) {
  if (($vars['view_mode'] == 'body') || ($vars['view_mode'] == 'bodyonly')) {
    $vars['theme_hook_suggestions'][] = 'nodereference__' . $vars['type'] . '__bodyonly';
  }
}

/*
function node_reference_preprocess_node(&$vars) {
  // The 'referencing_field' attribute of the node is added by the 'teaser'
  // and 'full node' formatters.
  if (!empty($vars['node']->referencing_field)) {
    $node = $vars['node'];
    $field = $node->referencing_field;
    $vars['theme_hook_suggestions'][] = 'node-reference';
    $vars['theme_hook_suggestions'][] = 'node-reference__' . $field['field_name'];
    $vars['theme_hook_suggestions'][] = 'node-reference__' . $node->type;
    $vars['theme_hook_suggestions'][] = 'node-reference__' . $field['field_name'] . '__' . $node->type;
  }
}
*/
